# Generated by Django 3.2.4 on 2021-07-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_regNo', models.IntegerField()),
                ('student_name', models.CharField(blank=True, max_length=50, null=True)),
                ('student_email', models.CharField(blank=True, max_length=50, null=True)),
                ('student_mobile', models.IntegerField()),
                ('created_at', models.DateField()),
            ],
        ),
    ]
