# Generated by Django 3.2.5 on 2021-07-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieBank',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Horror', 'horror'), ('Sci-fi', 'sci-fi'), ('Thriller', 'thriller'), ('Action', 'action'), ('Comedy', 'comedy')], max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('movie_type', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('release_date', models.DateField()),
                ('collection', models.DecimalField(decimal_places=2, max_digits=4)),
                ('director', models.CharField(max_length=100)),
            ],
        ),
    ]
