# Generated by Django 3.2.5 on 2021-07-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviebank',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
