# Generated by Django 3.2.4 on 2021-08-12 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_registration_number', models.IntegerField()),
                ('patient_name', models.CharField(blank=True, max_length=122, null=True)),
                ('patient_email', models.EmailField(blank=True, max_length=122, null=True)),
                ('patient_mobile_number', models.IntegerField()),
                ('admitted_at', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
